# This file is part of the Shared Kernel library.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: sql.yml }

services:
    lin3s.persistence.sql.event_store:
        class: LIN3S\SharedKernel\Infrastructure\Persistence\Sql\Event\SqlEventStore
        arguments:
            - "@lin3s.persistence.sql.pdo"
