# This file is part of the Shared Kernel library.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    lin3s.application.query.get_events:
        class: LIN3S\SharedKernel\Application\Event\GetEvents
        arguments:
            - "@lin3s.persistence.sql.event_store"
            - "@lin3s.routing.symfony.events_url_generator"
